---
version: '2'
services:
  awscliv1:
    image: normandesjr/awscliv1
    volumes:
      - ./files/dynamodb:/json
    command: create-resources.sh http://dynamodb:8000
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

